version: 2

jobs:
  test:
    docker:
      - image: circleci/node:10.15.1-jessie-browsers-legacy
    steps:
      - checkout
      - run: echo $PLAT_CREDS | base64 --decode --ignore-garbage > ./packages/api-tests/.test_config.json
      - run: yarn --cwd ./packages/api-tests   
      - run: node ./packages/api-tests/delete-all-users.js -c ./packages/api-tests/.test_config.json --force
      - run: yarn --cwd ./packages/api-tests test

workflows:
  version: 2

  unstable:
    triggers:
      - schedule:
          cron: "30 * * * *"
          filters:
            branches:
              only:
                - unstable
                - add-more-if-needed
    jobs:
      - test

